import images from "./constants/images";
// import { images } from "./constants/images";
import moment from "moment";
export const demandData = [
  {
    id: 1,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://assets.mixkit.co/active_storage/sfx/995/995-preview.mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Clothing", "dgsahdsdsadbsdsdbscccc", "Designer"],
    is_answered: "#Designer #dgsahdsdsadbsdsdbscccc",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 3,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 2,
    text_question:
      "I need a green Fancy dress for photo shoot. I need a expert designer to design the dress. I need it for May  0",
    image_question: images.shope,
    voice_question: null,
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Amand Joo",
    user_profile: images.profile,
    number_of_intreactions: 126,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 3,
    text_question:
      "I need a green Fancy dress for photo shoot. I need a expert designer to design the dress. I need it for May  0",

    image_question: null,
    voice_question:
      "https://assets.mixkit.co/active_storage/sfx/1714/1714-preview.mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 67,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 4,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: null,
    voice_question: null,
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 69,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 5,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 26,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 6,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 76,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 7,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      "how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 96,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 8,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 6,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 9,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 6,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 10,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: null,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 6,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 11,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 6,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 12,
    text_question:
      "I need a green Fancy dress for photo shoot. I need a expert designer to design the dress. I need it for May  0",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Joo Doe",
    user_profile: images.profile,
    number_of_intreactions: 6,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 13,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 3,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 14,
    text_question:
      "I need a green Fancy dress for photo shoot. I need a expert designer to design the dress. I need it for May  0",
    image_question: images.shope,
    voice_question: null,
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Amand Joo",
    user_profile: images.profile,
    number_of_intreactions: 126,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 15,
    text_question:
      "I need a green Fancy dress for photo shoot. I need a expert designer to design the dress. I need it for May  0",

    image_question: null,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 67,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 16,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: null,
    voice_question: null,
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 69,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 17,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 26,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 38,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 76,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 19,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      "how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 96,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 20,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 6,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 21,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 6,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 22,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 6,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 23,
    text_question: "I need drone camera for 4 days rent June 8- June 11",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Siham Joo",
    user_profile: images.profile,
    number_of_intreactions: 6,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
  {
    id: 24,
    text_question:
      "I need a green Fancy dress for photo shoot. I need a expert designer to design the dress. I need it for May  0",
    image_question: images.testimage,
    voice_question:
      "https://glassbrassparde.s3.us-east-2.amazonaws.com/NBSPLV+-+The+Lost+Soul+Down+(Slowed+Reverb).mp3",
    further_question: [
      " how much is the price?",
      "how much is the price?",
      "how much is the price?",
    ],
    demand_category: ["Designer", "Designer", "Designer"],
    is_answered: "#Designer #clothing",
    user: "Joo Doe",
    user_profile: images.profile,
    number_of_intreactions: 6,
    createdAt: moment(new Date(), "YYYYMMDD").fromNow(),
  },
];
