import images from "./constants/images";

export const shopesData = [
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages ",
    user: "Siham J",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope],

    shope_category: "Shose",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [
      images.shope,
      images.shope,
      images.shope,
      images.shope,
      images.shope,
      images.shope,
    ],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },

  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
  {
    id: 1,
    profile_images: [images.shope, images.shope, images.shope, images.shope],
    shope_category: "Bages",
    user: "Siham Joo",
    user_profile: images.profile,
  },
];
